name: 'normalize-git-branch-name'
author: Ole Hüter
description: 'Get a normalized git branch name and checksum from the GitHub ref'
branding:
  icon: 'hash'
  color: 'purple'
inputs:
  ref:
    description: 'The github.ref variable'
    required: true
  head-ref:
    description: 'The github.head_ref variable'
    required: false
outputs:
  original_name:
    description: 'The original branch name'
  name:
    description: 'The normalized branch name'
  hash:
    description: 'SHA1 checksum of the normalized branch name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ref }}
    - ${{ inputs.head-ref }}
